services:
  - mysql
  - postgresql

before_install:
  - gem install bundler

before_script:
  - bundle exec rake db:mysql:create
  - bundle exec rake db:postgresql:create

language: ruby
rvm:
  - 2.7.3
  - 3.0.1

env:
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=6.0.0"
  - "RAILS_VERSION=6.1.0"
